
name: CI

on:

  push:
    paths:
    - '**.jpg'  
  pull_request:
    paths:
    - '**.jpg'
    
    
jobs:

  move-jpg:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - name: Move all jpg files
        run: mv *.jpg Images

      - name: Commit our changes 
        run: |
          git config user.name ${{ secrets.USER_NAME }}
          git config user.email ${{ secrets.USER_EMAIL }}
          git add .
          git commit -m "JPG Mover Activated"
          git push
